import type { Assignment } from "../store/assignments/type";

export const exampleAssignments: Assignment[] = [
  {
    id: 1,
    title: "Math Homework",
    description: "Complete exercises 1-10 on page 25",
    startDate: "2023-04-10",
    dueDate: "2023-04-15",
    startTime: "09:00",
    endTime: "23:59",
    courseId: 101,
    maxAttempts: 3,
    gradingType: "points",
    totalPoints: 100,
    allowedFileExtensions: [".pdf", ".docx"],
    maxFileSize: 10485760, // 10MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
  {
    id: 2,
    title: "History Essay",
    description: "Write a 1000-word essay on the Industrial Revolution",
    startDate: "2023-04-05",
    dueDate: "2023-04-20",
    startTime: "00:00",
    endTime: "23:59",
    courseId: 202,
    maxAttempts: 1,
    gradingType: "percentage",
    totalPoints: 100,
    allowedFileExtensions: [".doc", ".docx", ".pdf"],
    maxFileSize: 20971520, // 20MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: true,
    isPublished: true,
  },
  {
    id: 3,
    title: "Chemistry Lab Report",
    description: "Write up the results of today's experiment",
    startDate: "2023-04-18",
    dueDate: "2023-04-18",
    startTime: "14:00",
    endTime: "15:00",
    courseId: 303,
    maxAttempts: 1,
    gradingType: "points",
    totalPoints: 50,
    allowedFileExtensions: [".pdf"],
    maxFileSize: 5242880, // 5MB in bytes
    isGroupAssignment: true,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
  {
    id: 4,
    title: "Programming Assignment",
    description: "Implement a binary search tree in Python",
    startDate: "2023-04-15",
    dueDate: "2023-04-25",
    startTime: "00:00",
    endTime: "23:59",
    courseId: 404,
    maxAttempts: 5,
    gradingType: "points",
    totalPoints: 200,
    allowedFileExtensions: [".py", ".ipynb"],
    maxFileSize: 1048576, // 1MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
  {
    id: 5,
    title: "Group Project Presentation",
    description: "Prepare slides for the final project presentation",
    startDate: "2023-04-10",
    dueDate: "2023-05-01",
    startTime: "09:00",
    endTime: "10:00",
    courseId: 505,
    maxAttempts: 1,
    gradingType: "percentage",
    totalPoints: 100,
    allowedFileExtensions: [".ppt", ".pptx", ".pdf"],
    maxFileSize: 52428800, // 50MB in bytes
    isGroupAssignment: true,
    isPeerReviewEnabled: true,
    isPublished: true,
  },
  {
    id: 6,
    title: "Art Portfolio",
    description: "Submit a portfolio of your best 5 artworks",
    startDate: "2023-04-01",
    dueDate: "2023-05-10",
    startTime: "00:00",
    endTime: "23:59",
    courseId: 606,
    maxAttempts: 3,
    gradingType: "points",
    totalPoints: 500,
    allowedFileExtensions: [".jpg", ".png", ".pdf"],
    maxFileSize: 104857600, // 100MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: true,
    isPublished: true,
  },
  {
    id: 7,
    title: "Physics Problem Set",
    description: "Solve problems 1-20 in Chapter 7",
    startDate: "2023-04-12",
    dueDate: "2023-04-19",
    startTime: "00:00",
    endTime: "09:00",
    courseId: 707,
    maxAttempts: 2,
    gradingType: "points",
    totalPoints: 100,
    allowedFileExtensions: [".pdf", ".jpg"],
    maxFileSize: 15728640, // 15MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
  {
    id: 8,
    title: "Language Oral Exam",
    description: "Prepare a 5-minute speech in Spanish",
    startDate: "2023-05-05",
    dueDate: "2023-05-05",
    startTime: "14:00",
    endTime: "16:00",
    courseId: 808,
    maxAttempts: 1,
    gradingType: "percentage",
    totalPoints: 100,
    allowedFileExtensions: [".mp3", ".wav"],
    maxFileSize: 52428800, // 50MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
  {
    id: 9,
    title: "Music Composition",
    description: "Compose a 2-minute original piece for piano",
    startDate: "2023-04-01",
    dueDate: "2023-05-15",
    startTime: "00:00",
    endTime: "23:59",
    courseId: 909,
    maxAttempts: 5,
    gradingType: "passFail",
    totalPoints: 100,
    allowedFileExtensions: [".mp3", ".midi", ".pdf"],
    maxFileSize: 104857600, // 100MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: true,
    isPublished: false,
  },
  {
    id: 10,
    title: "Literature Review",
    description: "Analyze 'To Kill a Mockingbird' and write a 500-word review",
    startDate: "2023-04-15",
    dueDate: "2023-04-22",
    startTime: "09:00",
    endTime: "23:59",
    courseId: 1010,
    maxAttempts: 1,
    gradingType: "points",
    totalPoints: 50,
    allowedFileExtensions: [".doc", ".docx", ".txt"],
    maxFileSize: 5242880, // 5MB in bytes
    isGroupAssignment: false,
    isPeerReviewEnabled: false,
    isPublished: true,
  },
];
